### PR TITLE
Implement entries() and update some docs

### PR DESCRIPTION
**Pull request by infinity0**
I needed this earlier than I expected so I've gone and implemented it too. :p Together my changes (including the earlier ones) increase the size from 1722 to 2002 bytes, I hope this is OK..

### CODE REVIEW

**Comment by WebReflection** [comment]
so, I've actually merged everything and updated tests to avoid errors (not sure how you tested stuff so far ...)

There is a failing test that is puzzling me, it's about `Map` and `-0` ... bear in mind, `-0` only

Do you mind having a look ? Then I'll be happy to publish this new major version

**Comment by infinity0** [comment]
Hmm, I am running `npm run minify && npm test` on cd26dd2a and I don't see failing tests... what error are you getting?

BTW, I'm about to file another PR to fix a bug to do with mutation-during-iterations, please review and publish that instead. :)

**Comment by WebReflection** [comment]
`npm run build` ... what does it give you, all green?

**Comment by WebReflection** [comment]
I always get this one:

```
  1) ES Collections test Map#set:
     AssertionError: o.has(-0)
      at Context.<anonymous> (/home/webreflection/code/es6-collections/test/index.js:175:5)
```

**Comment by infinity0** [comment]
Yes, it gives me all green...

~~~~
$ npm --version
1.4.21
$ node --version
v0.10.29
~~~~

**Comment by infinity0** [comment]
Can you try this?

~~~~
$ node
> -0 === +0
true
~~~~

**Comment by WebReflection** [comment]
I'm on io.js 1.0.x ... let's see tomorrow (30 past midnight here)

**Comment by infinity0** [comment]
hey, did you manage to figure this out?

**Comment by WebReflection** [comment]
So, this code **fails** with native Map in nodejs

```js
  var
      o = new Map(),
      generic = {},
      callback = function () {}
    ;
    o.set(callback, generic);
    assert(o.get(callback) === generic);
    o.set(callback, callback);
    assert(o.get(callback) === callback);
    o.set(callback, o);
    assert(o.get(callback) === o);
    o.set(o, callback);
    assert(o.get(o) === callback);
    o.set(NaN, generic);
    assert(o.has(NaN));
    assert(o.get(NaN) === generic);
    o.set("key", undefined);
    assert(o.has("key"));
    assert(o.get("key") === undefined);

    assert(!o.has(-0));
    assert(!o.has(0));
    o.set(-0, callback);
    assert(o.has(-0));
    assert(o.has(0)); // <-- this will fail
```

I have no idea why, but I've published anyway

**Pull request merged**
